spring:
  security:
    jwt:
      key: erasfiluhbnselir
      expire: 144
  application:
    name: learning-program-backend
  banner:
    charset: utf-8
  datasource:
    username: root
    password: 13974268
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
server:
  port: 1231